version: '3.8'

services:
  web1:
    build: .
    environment:
      SERVER_ID: SERVER-1
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: drugs
    depends_on:
      - postgres
    networks:
      - webnet

  web2:
    build: .
    environment:
      SERVER_ID: SERVER-2
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: drugs
    depends_on:
      - postgres
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2
    networks:
      - webnet

  postgres:
    image: postgres:latest
    container_name: postgres_drug_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: drugs
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d drugs"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  pgdata:
    driver: local
